apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vfeld/argocd-example-apps.git
    targetRevision: HEAD
    path: kustomize-guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: my-guestbook
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
